FROM golang:1.25-alpine

RUN go install github.com/githubnemo/CompileDaemon@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["CompileDaemon", "-build", "go build -o ./tmp/server .", "-command", "./tmp/server"]
